steps:
  # Build the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/insightcommand-461701/cx-futurist/frontend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'frontend'
    timeout: '900s'

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/insightcommand-461701/cx-futurist/frontend:latest']
    timeout: '300s'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/insightcommand-461701/cx-futurist/frontend:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '1000'
      - '--cpu-boost'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://cx-futurist-api-407245526867.us-central1.run.app,NEXT_PUBLIC_WEBSOCKET_URL=wss://cx-futurist-api-407245526867.us-central1.run.app,NODE_ENV=production'
    timeout: '300s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'