steps:
  # Build the optimized frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend-optimized:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend-optimized:latest'
      - '-f'
      - 'Dockerfile.optimized'
      - '.'
    dir: 'frontend'
    id: 'build-frontend'
    timeout: '900s'

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend-optimized']
    waitFor: ['build-frontend']
    timeout: '300s'

  # Deploy frontend to Cloud Run with optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend-optimized:${BUILD_ID}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '1000'
      - '--cpu-boost'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://cx-futurist-api-407245526867.us-central1.run.app,NEXT_PUBLIC_WEBSOCKET_URL=wss://cx-futurist-api-407245526867.us-central1.run.app,NODE_ENV=production'
    waitFor: ['build-frontend']
    timeout: '300s'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '50'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'  # 30 minutes total

# Enable automatic substitutions
substitutions:
  _DEPLOY_REGION: 'us-central1'