steps:
  # Build the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-backend'

  # Build the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api']
    waitFor: ['build-backend']

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend']
    waitFor: ['build-frontend']

substitutions:
  _REGION: us-central1

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1800s'  # 30 minutes