steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cx-futurist-api:latest', '-f', 'Dockerfile.production', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cx-futurist-api:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cx-futurist-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '540'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'LOG_LEVEL=INFO'

images:
  - 'gcr.io/$PROJECT_ID/cx-futurist-api:latest'

timeout: '1200s'