steps:
  # Build the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-backend'

  # Build the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api']
    waitFor: ['build-backend']

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend']
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:${BUILD_ID}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'API_HOST=0.0.0.0,API_PORT=8080,PINECONE_INDEX_NAME=cx-futurist'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,PINECONE_API_KEY=pinecone-api-key:latest,PINECONE_ENVIRONMENT=pinecone-environment:latest'
      - '--service-account'
      - 'cx-futurist-sa@$PROJECT_ID.iam.gserviceaccount.com'
    waitFor: ['build-backend']

substitutions:
  _REGION: us-central1

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1800s'  # 30 minutes