steps:
  # Build the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'frontend'
    id: 'build-frontend'

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend']
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/frontend:${BUILD_ID}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
    waitFor: ['build-frontend']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1800s'  # 30 minutes