steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cx-futurist-backend', '.']
    timeout: '600s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cx-futurist-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cx-futurist-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cx-futurist-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'AGENT_MODEL=gpt-4.1'
      - '--set-secrets'
      - 'OPENAI_API_KEY=cx-futurist-openai-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/cx-futurist-backend'

timeout: '1200s'