steps:
  # Build the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-backend'

  # Push the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cx-futurist/api']
    waitFor: ['build-backend']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1800s'  # 30 minutes