version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - API_HOST=0.0.0.0
      - PORT=8080
      - DEV_MODE=false
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: python -m uvicorn src.main_simple_ws:app --host 0.0.0.0 --port 8080 --ws-ping-interval 20 --ws-ping-timeout 60

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
        - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080
    depends_on:
      backend:
        condition: service_healthy

volumes:
  logs: